import Head from 'next/head'

export default function Dashboard() {
  return (
    <div>
      <Head>
        <title>FBL|Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div>
          Hello this is dash boar
        </div>
        <div>
          Number of Employess
        </div>
        <div>
          Remaining Fund
        </div>
        <div>
          Paid Fund
        </div>
        <div>
          Map of distribution of employees
        </div>
        <div>
          Real time transaction on the chain
        </div>
    </div>
  );
}
